baseurl = "https://actiphysique.vergnol.eu/"
title = "Actiphysique"
languageCode = "fr"
DefaultContentLanguage = "fr"
paginate = "10" # Number of posts per page
theme = "hugo-dpsg"

[Author] # Used in authorbox
  name = "Yannis Chkoundali"
  bio = "The Scout Master is the leader of this local scout group"
  avatar = "img/avatar.png"

[Params]
  description = "Welcome to our scout group!" # Site description. Used in meta description
  copyright = "Actiphysique" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  indexPager = true # Show pager navigation on index page
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02.01.2006" # Change the format of dates

[Params.style.vars]
  highlightColor = "#7ec590" # Override main theme color

[Params.logo]
  # image = "img/placeholder.png" # Logo image. Path relative to "static"
  header = "img/header.jpg" # Header image. Path relative to "static"
  title = "Actiphysique" # Logo title, otherwise will use site title
  subtitle = "Activité physique adaptée et coaching sportif" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.footer]
  text = "[Imprint and Privacy](/imprint)" # Extra text in footer row, understands markdown

# Custom menu items, normally controlled via front matter in /content files
[menu]
  [[menu.main]]
    identifier = "presentation"
    name = "Présentation"
    url = "/presentation"
    weight = 1

  [[menu.main]]
    identifier = "programme"
    name = "Programme surpoids / obésité"
    url = "/programme"
    weight = 2

  [[menu.main]]
    identifier = "coaching"
    name = "Coaching sportif pour tous"
    url = "/coaching"
    weight = 3

  [[menu.main]]
    identifier = "temoignages"
    name = "Témoignages"
    url = "/temoignages"
    weight = 4

  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contacts"
    url = "/contact"
    weight = 6
